import '@mantine/core/styles.css'
import '@mantine/dropzone/styles.css'
import '~/ui/styles/global.css'

import { ColorSchemeScript, Container, MantineProvider } from '@mantine/core'

import type { Metadata } from 'next'
import { theme } from '~/ui/theme'
import { ServiceNameHeader } from '~/ui/common/ServiceNameHeader'
import { ImagesProvider } from '~/contexts/images-context'

// TODO: 설명?
export const metadata: Metadata = {
  title: 'PICkle',
  description: 'Generated by create next ap',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>

      <body>
        <MantineProvider theme={theme}>
          <ImagesProvider>
            <Container
              maw={385}
              size="responsive"
              p={0}
              style={{ position: 'relative' }}
            >
              <Container>
                <ServiceNameHeader />
              </Container>
              {children}
            </Container>
          </ImagesProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
