import '@mantine/core/styles.css'
import '@mantine/dropzone/styles.css'
import '~/ui/styles/global.css'

import { ColorSchemeScript, Container, MantineProvider, createTheme } from '@mantine/core'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next ap',
}

const theme = createTheme({})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
			</head>

			<body>
				<MantineProvider theme={theme}>
					<Container maw={385} mih={'100dvh'} p={0} m={0} mx='auto'>
						{children}
					</Container>
				</MantineProvider>
			</body>
		</html>
	)
}
